### ISSUE TITLE
Minify extension src code

### ISSUE THREAD

**Issue by ShMcK** [coderoad/coderoad-vscode#162]
Not a big deal, but VSCode warns that the tutorial should be minified into fewer files for performance.

Due to the nature of having a Node app & a web app, this is a big difficult to achieve. 

Priority is low for now.

**Comment by zardoy** [comment]
Does it relate to the extension bundle itself? This extension has biggest extension size I've ever seen 27,5 MB .vsix and more than 100 MB unarchived !! This is absolute record. (sizes are 10-based)

The second record belongs to Microsoft Live Share extension, but this is closed-source project and they don't care at all.

I don't think this is good, your extension in my case was installing forever.

Some considerations:

- do not include maps, I don't think user needs them
- do not include node_modules and instead bundle the code

Of course I don't recommend look into VSCode docs and use neither webpack nor react-script.

And of course I would highly recommend esbuild with (probably with several entry points).

**Comment by ShMcK** [comment]
Thanks @zardoy. I had hoped to bundle the code. I ran into issues with the path mapping.

It's a bit complicated as there is a web app inside of a vscode app. 

I absolutely agree. Create react app is a dependency beast.

**Comment by ShMcK** [comment]
After bundling, and some work removing heavy dependencies - I've gotten the size to around 1mb.
