### ISSUE TITLE
Not Working on Windows

### ISSUE THREAD

**Issue by ShMcK** [coderoad/coderoad-vscode#227]
CodeRoad currently does not run on Windows. Quarantine has made it harder to test these things.

- [x] configure git bash in the .vscode/settings.json. See an example below from https://dev.to/simbo1905/how-to-integrate-git-bash-with-visual-studio-code-on-windows-3217. 
- [x] Ensure that Git Bash is set as the default terminal when called child processes.
- [x] Ensure that Git Bash exists
- [x] Verify that all file paths use the `path.join(a, b, c)` format. 
- [x] Check the `/vscode-resource` replace line [in webview/render.ts](https://github.com/coderoad/coderoad-vscode/blob/0bd760793f07d812e268f3a3b153351a00dbcb02/src/webview/render.ts#L39) . If the webview loads fine, this is likely not the cause.

**Comment by hahn-rho** [comment]
Unable to install because, the depending extension 'coderoad.coderoad' compatible with current version '1.27.2' of VS Code is not found.

Upon trying to install with .vsix: Unable to install because, the depending extension 'coderoad.coderoad' compatible with current version '1.27.2' of VS Code is not found.

Will try and install from github-master

**Comment by ShMcK** [comment]
@hahn-rho thanks for the issue!

Are you on a windows computer?

There is also a VSCode requirement of `"vscode": "^1.40.0"`. You may need to update your current version of VSCode.

It should be easier to install from the vscode marketplace: https://marketplace.visualstudio.com/items?itemName=CodeRoad.coderoad

Also bear in mind, we just opened this up recently and haven't tested it much on other environments yet. Covid 19 has made testing a lot more difficult.

**Comment by hahn-rho** [comment]
! talk about a quick response. Yes, windows. I already tried the marketplace link... aaaand I just realised that installing Git will probably help. If that was the only problem I'll thank you now, otherwise I'll post how I resolved the issue.

**Comment by ShMcK** [comment]
And thank you for your early adoption! In the next release, it will check for git before launching. See #228 .

I'm pretty certain that it won't work on Windows at this point. We're working on it, and have identified a few cross platform issues.

We may have a version available within the next week or two. I'd recommend trying again once this issue is closed.

**Comment by hahn-rho** [comment]
Git installed, CodeRoad now installed :D 

But no "start" option in right panel. I'll keep at it.

**Comment by ShMcK** [comment]
@hahn-rho it won't work on Windows yet, but it's in the works

**Comment by ShMcK** [comment]
@hahn-rho version 0.2.3 shoudl work with Windows. It's available in the store shortly.
