### ISSUE TITLE
VSCode 1.39.2 support

### ISSUE THREAD

**Issue by AdamZaczek** [coderoad/coderoad-vscode#264]
**Is your feature request related to a problem? Please describe.**
We'd love to support coderoad inside strove.io by default. We use vscode 1.39.2 for now. Could we have support for this version? I'm almost 100% sure API will be compatible.

**Describe the solution you'd like**
Add
  "engines": {
    "vscode": "^1.39.2"
  },

And 
under "dependencies" key
"@types/vscode": "^1.39.2",

To package.json

**Additional context**
So far, users using strove are unable to access coderoad and we're not ready to bumb vscode version just yet.

**Comment by ShMcK** [comment]
@AdamZaczek I can send you a build with the above requirements to your email for testing, would that work?

**Comment by ShMcK** [comment]
@AdamZaczek I've released a version that runs on VSCode v1.39.2. 
It should be available in the store soon as v0.2.4.

Luckily no breaking changes!

**Comment by AdamZaczek** [comment]
Awesome, we're adding it Strove by default!
