### ISSUE TITLE
Cannot get past first lessons

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#265]
I cannot get past the first lesson in either of the tutorials.

First lesson of NPM tutorial (add "author" to package). I add the "author", hit save, and it fails...
<img width="902" alt="Screen Shot 2020-04-14 at 11 46 02 AM" src="https://user-images.githubusercontent.com/20648924/79251302-940dd880-7e45-11ea-9a49-37e6a9353511.png">

It's showing that they pass when I run the dedugger...
<img width="903" alt="Screen Shot 2020-04-14 at 11 47 30 AM" src="https://user-images.githubusercontent.com/20648924/79251468-c9b2c180-7e45-11ea-956c-6a8490c56797.png">

or test it in the terminal...
<img width="437" alt="Screen Shot 2020-04-14 at 11 49 18 AM" src="https://user-images.githubusercontent.com/20648924/79251612-01216e00-7e46-11ea-8691-46bc2e4d9411.png">

Same issue occurs on the Basic Node and Express tutorial for me. Not quite sure what the problem is.

Any advice on getting these working @ShMcK? Seems like it might be something on my end.

node: 12.16.1
npm: 6.13.4
vs code: 1.44.0
coderoad: 0.2.3

**Comment by ShMcK** [comment]
@moT01 it seems from the error messages that the tutorial requires Node 12, instead of Node 10. I'll make a note to change the tutorial to support Node 10.

If you'd like, you can try running it with Node 12. I use this tool to change my versions, it's pretty great:

https://github.com/tj/n

**Comment by ShMcK** [comment]
It seems the tutorial requires Node 12 to run, but seems to be running on Node 10 from the debug output.

But you mentioned you're using Node 12, hmm...

I've added a tutorial dependency feature recently for checking these versions, but haven't added it to the tutorial yet. I'll also change the tutorial later today to allow for Node 10 support. It seems to just come down to the tutorial using the `fs.promise`s API.

Thank you again for your feedback, and hope to have this resolved soon :)

https://github.com/tj/n

**Comment by moT01** [comment]
Thanks. Yea, that was the problem. It did show me node 12 in the terminal, but the debugger was showing node 10. I put nvm on my machine to easily switch between node versions a while back and it seems like the debugger defaulted to my default setting on there or something.

Anyway, this tool looks really awesome - nice job! 👍

**Comment by ShMcK** [comment]
@moT01 thanks again! I've updated the two displayed tutorials to support Node v0.10.
