### ISSUE TITLE
Progressive Hints on failed attempts

### ISSUE THREAD

**Issue by ShMcK** [coderoad/coderoad-vscode#313]
Provide hints on a failed step, where each new fail attempt introduces a new hint.

Tips can be written in Markdown, eg:

```
**Hints**
- First hint
- Second hint
- Final hint
```

**Comment by moT01** [comment]
Wonder if these hints should stay displayed. So if I navigate back to a previous lesson to see what I did there, the hints will show and maybe help me with the current lesson.

**Comment by ShMcK** [comment]
The "get hint" button could be put on the failed test message, forcing users to try first?

Hints could also be put into an accordion-style list, allowing users to open them up to see all previous hints.

Currently, if you navigate to previous lessons you don't see the previous steps/tasks (or hints associated with those steps). Are hints needed for past steps that have been completed? Could that info be put into the "Learn" content?
