### ISSUE TITLE
Remove short decriptions?

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#332]
I'm wondering if CodeRoad needs these...
<img width="737" alt="Screen Shot 2020-05-14 at 10 27 54 AM" src="https://user-images.githubusercontent.com/20648924/81953788-b1ad9980-95cd-11ea-8818-47943bfdf849.png">

I really like them, and it looks good on the introduction page. But I'm struggling to come up with a mini description for things. They always just basically say the same thing that the title does.

I would just leave this for now. I'll see if I can work on better info for these spots. Just throwing the idea out there. Maybe if I just remove them from the markdown they wouldn't show up.

**Comment by ShMcK** [comment]
Do you think it's worth parsing the first 100 or so characters, or just skip a description?

**Comment by moT01** [comment]
Parsing the first part of the description? Yea, I thought about that - it's not a bad idea.

I just gave it a quick test, and I can simply put an space in there and nothing will show up....
<img width="264" alt="Screen Shot 2020-05-14 at 10 39 35 AM" src="https://user-images.githubusercontent.com/20648924/81955084-4664c700-95cf-11ea-88b8-d5ff9db3d872.png">

So we have that option, which is fine it I want to omit those. Side note: I do get an error when parsing if there's no space.

**Comment by moT01** [comment]
I just copy/pasted the first part of the instructions to see what it might look like...

<img width="326" alt="Screen Shot 2020-05-14 at 10 44 32 AM" src="https://user-images.githubusercontent.com/20648924/81955656-fe926f80-95cf-11ea-902a-43d72eb7efd5.png">

Not bad.

**Comment by ShMcK** [comment]
Removed in the build tool next release at https://github.com/coderoad/coderoad-cli/pull/5.
