### ISSUE TITLE
Markdown styling adjustments

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#345]
Not sure if you have some css that is affecting the markdown styles or what. But there's a few things that aren't displaying quite like I would expect.

New paragraphs don't have an empty line/space. And tables don't have any borders, background, etc...

Markdown:
<img width="342" alt="Screen Shot 2020-05-17 at 2 57 21 PM" src="https://user-images.githubusercontent.com/20648924/82158644-c351a400-984e-11ea-8177-68d0c0046903.png">

CodeRoad:
<img width="308" alt="Screen Shot 2020-05-17 at 2 57 05 PM" src="https://user-images.githubusercontent.com/20648924/82158647-c51b6780-984e-11ea-924b-6215fa186d43.png">

This table doesn't look too bad, but other ones with large amounts of data look rough. I could probably find a way to put empty lines in the paragraphs if I need to.

Bold letters are pretty subtle:
<img width="48" alt="Screen Shot 2020-05-17 at 7 45 37 PM" src="https://user-images.githubusercontent.com/20648924/82164617-163f5180-9877-11ea-9454-f37a684f8bea.png">
^ the `c` is bold

**Comment by ShMcK** [comment]
CodeRoad is currently using `markdown-it`. It has some limitations, but can probably be configured to support tables.

I'd like to explore using MDX first (#242), but if setting it up is too much trouble, I'll see what I can do with the markdown-it output. MDX is much more configurable, allowing you to even add React components to the markdown.
