### ISSUE TITLE
Admin mode, build mode, review mode?

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#348]
So my tutorial is breaking the 100 lessons mark. It can be tough to make changes and review them. For instance, if I make a change to lesson 99 and want to see it. I have to go through all the lessons to get there - I don't think there's an easy way around it. It's manageable for now, since I am not needing to frequently go back and fourth. But I can see this being a real pain at times. I can deal with it if I need to.

**Comment by beaucarnes** [comment]
@ShMcK I also really want to be able to skip ahead to a future lesson for testing purposes. Please make this feature a priority. It will save a lot of time.

**Comment by ShMcK** [comment]
Definitely, I hope to spend a lot more time on build tools. I have a plan I'm happy to share.

I can map out my current plan for a build tool - I'd love to hear feedback, suggestions, priorities, and clarification of the requirements.

### Summary

Progressively working towards a VScode extension for creating tutorials. Eventually, all features should be encompassed within the app, meaning no more need for markdown or yaml in tutorial development - eventually everything can be written directly in JSON. 

### Phases

- [x] **Phase 1: Build Tool**:
A build tool CLI. (`coderoad build`)This was basically the MVP and may require bits of future development.

- [x] **Phase 2: Validation**:
Validation tools (`coderoad validate`) to ensure the tutorial builds correctly. Again, the tool may need some minor work.

- [ ] **Phase 3: View/Edit Text**
An Electron app for traveling through level/step text. Should be flexible to consider internationalization.
Time estimate: 4 weeks
1. should be able to travel through different levels/steps and view text
2. should be able to edit the README file and update the text

- [ ] **Phase 4: Edit Text Inline**
An Electron web app that saves directly to JSON.
Time estimate: 2 weeks
1. should be able to edit markdown text inline
2. no more need for a TUTORIAL.md file, data saves directly to JSON. No build needed for markdown.


- [ ] **Phase 5: View/Edit Code**
A VSCode extension that uses the web app above alongside real code, leveraging code from the previous project.
Time estimate: 4 weeks
1. should be able to travel through different levels/steps and view the tutorial code
2. should be able to edit the tutorial code in place
3.

- [ ] **Phase 6: Edit Configurations**
A more fully-featured continuation on the VSCode extension mentioned above.
Time estimate: 1 week for tutorial configs, 1 week for level/step configs
1. should be able to edit the tutorial configuration in a form
2. should be able to edit the level/step configurations in a form
3. no more need for a build cli script or yaml config, as tutorials save directly to JSON

- [ ] **Phase 7: New Tutorial Setup**
A way to quickly start with a working tutorial boilerplate. Should wait until we have a clearer idea of what a working tutorial is.
