### ISSUE TITLE
Horizontal scroll bar not needed

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#366]
Horizontal scroll bar isn't needed...

![Screen Shot 2020-06-15 at 8 31 47 PM](https://user-images.githubusercontent.com/20648924/84721903-69282980-af47-11ea-856b-8ccc1b46e220.png)

Must be a little extra margin on something maybe? The text just doesn't wrap soon enough.

Edit: these actually only seem to show up on firefox... oh firefox

**Comment by ShMcK** [comment]
Seems related to [this issue](https://stackoverflow.com/questions/39738265/firefox-displays-unnecessary-horizontal-scrollbar).

I think I'll close this one for now as low priority, but may re-open in the future.
