### ISSUE TITLE
Inconsistent directories

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#371]
The commands on setup seem to be relative to the "directory" if you have one.
The watchers seems to be relative to the project root. 

For example, on setup (if I include `directory: coderoad`) - the cwd would be that coderoad folder. But the watchers cwd would be the project root. I haven't used commands on a per lesson basis, but I assume it would be the same for those.

Not a big deal, but it could maybe be consistent I guess

**Comment by ShMcK** [comment]
That's a good point. 

Thoughts on switching watches to run from a directory? This would be a breaking change, but with buy-in from a small group of tutorial creators, we can make it happen.

**Comment by moT01** [comment]
Definitely not a priority. In fact, now that I know how to hide the folders, probably don't even the directory in the yaml. But I would keep it - nice to keep things isolated.

I wouldn't object if you want to do it. It would be an easy search and replace in the yaml file to update the repos.
