### ISSUE TITLE
Hints don't follow old instructions

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#374]
If I navigate to a previous challenge, the hints that show are still for the challenge I am on.

**Comment by ShMcK** [comment]
In the current design, hints are for the current task.

The learn section can change, but the task at hand remains the same. 

But it may be worth considering a redesign. What's the benefit of showing the user previous tasks?

**Comment by moT01** [comment]
I guess it's just a nice feature. If it's a real pain, it's fine for now. But if I get to a lesson that I'm stuck on, often times something I learned in a previous lesson can help me figure out what to do. As well as just being able to review things. When someone completes an entire tutorial, the only way to go back and see what they've done, is to do the whole tutorial again (if there's no ability to navigate around the challenges). Actually, they may not be able to go back through it at all if it's completed - not sure what happens if you click "continue tutorial" after you've completed it. I want to say that you can't go back once you get to that last page.

**Comment by ShMcK** [comment]
closed with #386
