### ISSUE TITLE
Optional Run tests button / disable run tests on save

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#376]
I'm not entirely sure if this is needed yet. But I want to say it will be for the projects.

Basically have a "run tests" button that runs all the tests, but it's optional. And disables the tests from running on save.

Speaking of that, it would be nice to have the option to disable the tests from running on save in general. It's a great feature, but sometimes not necessary.

**Comment by ShMcK** [comment]
Currently, we do have environmental variables for this - I believe they should work in Strove now.
- `DISPLAY_RUN_TEST_BUTTON` - shows a run test button in the footer
- `DISABLE_RUN_ON_SAVE` - stops running tests on save

It would be great if the configuration of settings was possible on some kind of settings page as well.
