### ISSUE TITLE
Images in the docs are not working

### ISSUE THREAD

**Issue by TomasHubelbauer** [coderoad/coderoad-vscode#424]
Hi, just passing by your repo and I have noticed the images in your docs don't work:
https://coderoad.github.io/docs/overview
> <img width="822" alt="image" src="https://user-images.githubusercontent.com/6831144/89409410-4f72b980-d722-11ea-9e63-59789d217531.png">
I figured I'd bring this to your attention in case this is not known yet.

**Comment by ShMcK** [comment]
Thanks @TomasHubelbauer!

I pushed those docs last night but seems the static asset paths don't work when deployed. 

Lesson learned, always test!
