### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jordanliu** [coderoad/coderoad-vscode#425]
Is there a logo for CodeRoad? For the docs and vscode icon, if not - are there any suggestions on what it should look like?

Related: #176

**Comment by ShMcK** [comment]
Currently no selected logo, but open to suggestions!

The original intention in the name is about following a 'path' or a 'road' towards a goal.

**Comment by jordanliu** [comment]
@ShMcK I made some mockups, went for a little abstract design. 

Used a green/yellow gradient but can be changed if another colour scheme is provided.

V1:
![Frame 1](https://user-images.githubusercontent.com/9423525/89469991-b1deb080-d748-11ea-9cf9-fe462679ca22.png)

V2:
![Frame 2 (2)](https://user-images.githubusercontent.com/9423525/89470281-72fd2a80-d749-11ea-8ce6-4ad75e4714ab.png)

V3:
![Frame 3](https://user-images.githubusercontent.com/9423525/89470001-b73bfb00-d748-11ea-912a-9108da5ad8f3.png)

Please let me know what you think :smile:

**Comment by ShMcK** [comment]
I'm leaning towards V1 for its simplicity and minimalism. Always open to other ideas though if inspiration strikes.

In terms of color scheme, I think it makes sense to align with the VSCode default color scheme for now. 

Out of curiosity, what would the logo look like if it were a bit more "ribbon-like", as in the VSCode logo?

**Comment by jordanliu** [comment]
@ShMcK see updates - changed to blue, made some variations and attempted ribbon. Let me know how they are now 😸 

V1
![Frame 1 (1)](https://user-images.githubusercontent.com/9423525/89481088-f9733580-d764-11ea-9474-640c8f272a78.png)

V2
![Frame 2 (3)](https://user-images.githubusercontent.com/9423525/89481091-faa46280-d764-11ea-8393-bd5a494b4f8c.png)

V3
![Frame 3 (1)](https://user-images.githubusercontent.com/9423525/89481099-009a4380-d765-11ea-9091-989d5a23e645.png)

V4
![Frame 4 (1)](https://user-images.githubusercontent.com/9423525/89481511-e4e36d00-d765-11ea-8222-059b5f806b33.png)

**Comment by ShMcK** [comment]
Now I'm thinking v4 is too "vscode-like". 

The simplicity of the 3 lines could make for some interesting animations.

@jordanliu - In your opinion, what do you consider the primary difference between v1 and v2?

**Comment by jordanliu** [comment]
@ShMcK The difference between v1 and v2 are the shading of the gradients, look at the tip of the > and you'll see there is an interception

v1 is a bit more plain while v2 has more depth

**Comment by ShMcK** [comment]
Oh, I mean in terms of "symbolism" of the logo, what's the difference in the interpreted meaning between v1 & v2?

To me, v1 looks more like a code symbol as a coherent `>`

v2 looks more like a shape that folds out at each corner.

**Comment by jordanliu** [comment]
> Oh, I mean in terms of "symbolism" of the logo, what's the difference in the interpreted meaning between v1 & v2?
> 
> To me, v1 looks more like a code symbol as a coherent `>`
> 
> v2 looks more like a shape that folds out at each corner.

Well, v1 and v2 are intended to represent the same meaning. It's just that v2 has a more detailed shape, but both represent the same ">".

**Comment by ShMcK** [comment]
So far v1 is my favorite. 👍 

It may help to go into restrictions for a logo as well.

1. it should look good small. 
  - VSCode marketplace sizes: 128x128, 256x256 (retina)
  - I also hope to use the icon as the SVG file icon (16x16) for the loaded web app. Possibly too small to do much. See the top left corner below. 

![image](https://user-images.githubusercontent.com/4660659/89484480-6f6ea100-d753-11ea-87a5-2ad55cfcc75b.png)


- I hope to later put the logo into the side menu (see below), meaning that there should be a single color variant that is recognizable as a centered 24x24 SVG

![image](https://user-images.githubusercontent.com/4660659/89484372-3fbf9900-d753-11ea-899c-cbe1631bd395.png)

**Comment by jordanliu** [comment]
The current size you see there is 128x128

16x16:
![Frame 6](https://user-images.githubusercontent.com/9423525/89485093-0183a300-d76e-11ea-9fac-9f7b6dda4829.png)

24x24:
![Frame 7](https://user-images.githubusercontent.com/9423525/89485156-2841d980-d76e-11ea-8a66-9a97e32a499b.png)


They're made using vectors so svg is an easy export, if the design is confirmed. I'd love to implement the new logo in the docs :smile:

**Comment by ShMcK** [comment]
That's recognizable enough. Let's go with that logo.

I can implement it in the extension once you've added the different sizes.

**Comment by jordanliu** [comment]
I'm on it

**Comment by ShMcK** [comment]
The logo might look good on a banner at the top of the README as well

**Comment by jordanliu** [comment]
@ShMcK check out #433 - i'll create a banner once some creative juices flow :smile:

**Comment by jordanliu** [comment]
ps: @ShMcK should consider changing the organization picture to the logo, it would look neat

**Comment by ShMcK** [comment]
The org logo is recommended at 500 by 500 pixels, looks a bit pixelated at 200.

**Comment by ShMcK** [comment]
I'm not sure how familiar you are with React, but the "Start" page in the app could use some logo/design love.

https://github.com/coderoad/coderoad-vscode/blob/master/web-app/src/containers/Start/index.tsx

It can be developed using [React storybook](https://storybook.js.org/docs/guides/guide-react/), a development playground.

**Comment by jordanliu** [comment]
I'm familiar with react, I'll give it some love as soon as I can. Any special requests?

**Comment by ShMcK** [comment]
@jordanliu we can follow up at #435. Also sent you an invite to the org!

I've added the logo config to the vscode marketplace, should be ready to go with the next release. I'll close this issue for now.
