### ISSUE TITLE
The progess bar is too slow

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#429]
The progress bar takes quite a while to show me how far I am at the end of a lesson. I think it should be faster. Start it fast, and make it slower the further it gets.

**Comment by ShMcK** [comment]
If someone is interested in tackling this one, let me know.

The code is in https://github.com/coderoad/coderoad-vscode/blob/master/web-app/src/containers/Tutorial/components/ProgressPie.tsx

And can be developed using storybook. Run `yarn install-all` then `yarn storybook` to get started.
