### ISSUE TITLE
Tutorial Issue on Windows

### ISSUE THREAD

**Issue by HeIp** [coderoad/coderoad-vscode#447]
1. Started Learn NPM package json
2. Click on run after adding author property to package.json
3. See error

**Expected behavior**
Expected to move on to the next section

**Screenshots**
![image](https://user-images.githubusercontent.com/31706214/90407710-cd18bc80-e074-11ea-958a-4ae2ef8ada05.png)
Started trying out the plugin but got stuck.

**Desktop (please complete the following information):**
 - Platform: Windows
 - OS: Windows 10
 - Version Version	10.0.19041 Build 19041

**VSCode (please complete the following information):**
 - Version 1.48.0

**Node (please complete the following information):**
 - Version 12.8.1

**Git (please complete the following information):**
 - Version 2.27.0.windows.1

**Comment by ShMcK** [comment]
I'm guessing the test runner didn't install correctly. Let's find out why.

In the terminal, can you type

```
cd coderoad
npm install
```

Let me know if any errors come up.

To open a terminal in vscode, press ctrl + backtick (^`)

**Comment by HeIp** [comment]
Did as instructed, failed again.
here's a picture of the contents:
![image](https://user-images.githubusercontent.com/31706214/90413352-554e9000-e07c-11ea-8e9c-714201f28d3e.png)

**Comment by ShMcK** [comment]
Can you try closing the CodeRoad window, then re-launching it?

Choose the `continue` option.

**Comment by HeIp** [comment]
Test Runner still failed after doing so

**Comment by ShMcK** [comment]
Definitely shows I'll have to add some logging to debug issues like these in the future.

What happens if you run `npm test` in the command line?

**Comment by HeIp** [comment]
package.json
    1) should have a valid "author" key


  0 passing (8ms)
  1 failing

  1) package.json
       should have a valid "author" key:
     AssertionError [ERR_ASSERTION]: no "author" key provided
      at Context.<anonymous> (test\packagejson.test.js:11:12)
      at processImmediate (internal/timers.js:458:21)



npm ERR! Test failed.  See above for more details.

**Comment by ShMcK** [comment]
Maybe just one more test.

Can you go in the `coderoad` directory (`cd coderoad`), then run:

```shell
./node_modules/.bin/mocha
```

If that works, try running:

```shell
./node_modules/.bin/mocha --reporter=mocha-tap-reporter
```

**Comment by HeIp** [comment]
As a note I would like to clarify that I ran those commands inside the coderoad folder
./node_modules/.bin/mocha
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ShMcK** [comment]
Looks like the tutorial won't run on windows because of the path to the test runner executable. Only Linux/Mac for now.

I'll try to put in a fix later today and re-publish the tutorials.

Thank you greatly for your help @HeIp !

**Comment by HeIp** [comment]
No problem, @ Me when you do so

**Comment by ShMcK** [comment]
Could you try running the tutorial again from a **different** workspace? I've fixed the executable paths.

**Comment by HeIp** [comment]
No change

**Comment by ShMcK** [comment]
I tried testing on a Windows VM, but was pretty slow and frustrating.

I've ordered a Windows computer that arrives tomorrow and hope to debug and better test releases.

**Comment by HeIp** [comment]
Oof

**Comment by ShMcK** [comment]
My shiny new $100 Windows computer arrived. It's about the size of two credit cards, didn't expect that.

Good news though: I've found a few issues and will put in a fix.

I'll close this ticket in favor of the more descriptive #451. The issue seems to match up with your description exactly.

Until then, I've removed the "Windows" from supported OS's in the README. Coming soon!
