### ISSUE TITLE
Add a restart whole tutorial button

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#476]
I'm not sure if this is necessary, but it might be nice to have a button to restart a tutorial from the beginning. Opening an issue for discussion.

**Comment by ShMcK** [comment]
I can see this as a problem with the online version where's it's not easy to open a new folder.

So far it sounds like a "tutorial settings" may be helpful, something like how GitHub has repo settings.

**Comment by ShubhamCanCreate** [comment]
I am thinking to take up this issue. Here's what I think needs to be done.
- Show a settings menu which contains the reset option(I have attached an image which has the settings icon on the top right. Clicking on it would open the settings menu. Any suggestions?)
- Send an event to reset the state
- Invoke some vscode api to reset the files. (Do we also need to delete commits?)

![image](https://user-images.githubusercontent.com/52590791/133033123-993b4095-218f-47cc-a167-f93df2eb9f83.png)

**Comment by ShMcK** [comment]
### Settings Page
A settings page makes a lot of sense. There is definitely more functionality that could be added there.

### Resetting a Tutorial
There is some existing logic for resetting to a commit in `src/services/reset/index.ts`. 
I think the idea would be to reset to the hash of level 1 step 1. 

A step can contain more than one hash, so you'd have to take the last one.

Also note that the reset events needs to be passed to the local vscode server (the code inside of src). The web portion does not have access to run on the file system.

**Comment by ShubhamCanCreate** [comment]
Yes. I found an already existing settings page. I've also reused the **Reset** button component if that's ok.
Should I open a PR?

[Feature branch](https://github.com/ShubhamCanCreate/coderoad-vscode/tree/feat/reset-whole-tutorial)
![settings-page](https://user-images.githubusercontent.com/52590791/133217492-827eebd3-0392-439b-a084-6e8691bc1fbd.gif)

**Comment by moT01** [comment]
Would there be a way to make it completely reset to the point where it's as if you just started a tutorial? Like empty out the workspace folder, and re-clone the repo or something?

**Comment by ShMcK** [comment]
That's also possible.

Deleting all files is a bit scary, maybe reset to the empty first commit, then run the init action again.

**Comment by ShubhamCanCreate** [comment]
- Do we end up in a unclean state if we reset to level 1 step 1?
- Is there a way to avoid running `yarn build` everytime I want to see the code changes.

**Comment by ShubhamCanCreate** [comment]
So I have made a PR on based of the first solution which is reseting to level 1 step 1. I think that works fine and we can improve further on this base.
