### ISSUE TITLE
Error when using # in text

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#479]
I tried to use `#` in a number of lessons to describe comments in bash, I get an error when building and the JSON for that lesson shows up empty if I remember correctly.

Basically, using `#<space>` gives an error. For now, I just didn't include the space - meaning I put text right after it, and it works - e.g. `#<text>`.

I believe this is accurate, not a big problem.

**Comment by ShMcK** [comment]
Resolved in https://github.com/coderoad/coderoad-cli/releases/tag/v0.7.0
