### ISSUE TITLE
Having git configured to gpgsign commits is interfering with tutorial

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-vscode#520]
From one of our users:

"After starting container, CodeRoad plugin, and starting tutorial, it seemed to not run setup at all (the pop-ups with run commands weren't displayed). After updating rdb-alpha with https://github.com/freeCodeCamp/rdb-alpha/pull/7 setup seems to run, however running tests still fails. When gpgsign option in git config is commented out, everything works fine."

I haven't attempted to replicate this. I will give it a try and post what I find - maybe it's something with the container we are using. I don't think so though. Assuming it's not, CodeRoad could maybe use a check for that - similar to, or along with, the check for a git username and email:
![Screen Shot 2021-11-03 at 9 13 45 AM](https://user-images.githubusercontent.com/20648924/140076872-141a10de-9300-46dc-abeb-bb2e5e47a3c0.png)

Or perhaps a way around the signed commits. Not sure exactly what is breaking, maybe there's a simpler way around it. It's not a big issue, just thought I would point it out.

**Comment by ShMcK** [comment]
I can reproduce it by adding `commit.gpgsign = true` to my .gitconfig. I'll look into the cause/solution.

**Comment by ShMcK** [comment]
The PR in #521 may not resolve the issue, but it will display to the user a clear message of why it failed.
