### ISSUE TITLE
Regarding psql --username and dbname

### ISSUE THREAD

**Issue by jillawar** [coderoad/coderoad-vscode#558]
**Describe the bug**
This doesn't seems to be bug, but :
when I first logged into psql using > psql --username=freecodecamp dbname=postgres , it was successful 
but I closed terminal and then tried to do the same i.e to login I type the exact above line.. it is throwing error (attached the image)

**Expected behavior**
I just want to login to it and start learning the course "Learn Relational Databases by Building a Mario Database".

**Screenshots**

**Desktop (please complete the following information):**
 - Platform: Windows,
 - OS: Windows 10
 - Version : 10.0.19043

**VSCode (please complete the following information):**
 - Version : 1.63.2

**Node (please complete the following information):**
 - Version [e.g. 12.4]

**Git (please complete the following information):**
 - Version [e.g. 2.24.1]

**Additional context**
![Capture](https://user-images.githubusercontent.com/73386030/147949625-dda80d37-b12c-4f0c-9e60-d3c30b5e654c.PNG)

**Comment by jillawar** [comment]
i closed this has the issue is resolved..
What I did was to restart the same project using URL. and when I started the lessons, it logged in.

**Comment by ShMcK** [comment]
Interesting, thanks for the tutorial feedback. I'll ping @moT01 for awareness.

**Comment by jillawar** [comment]
Thank you, Sir.

**Comment by jillawar** [comment]
Hello Sir,
It appears if we enter the below code (which i found in the course URL), then we need not restart the course, we can continue from where we left by using the starting code : psql --username=freecodecamp dbname=<db>
The code is : 
	sudo touch ~/pg.log
        sudo chmod 777 ~/pg.log
        sudo touch ~/queryResults.log
        sudo chmod 777 ~/queryResults.log
        sudo cp ~/project/.freeCodeCamp/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
        sudo cp ~/project/.freeCodeCamp/postgresql.conf /etc/postgresql/12/main/postgresql.conf
        sudo cp ~/project/.freeCodeCamp/.bashrc ~
        sudo cp ~/project/.freeCodeCamp/.psqlrc ~
        sudo chown -R postgres:postgres /var/lib/postgresql/12/main
        sudo service postgresql stop
        cd .freeCodeCamp && npm install
        sudo service postgresql start
.........
This was amazing to find out, I'm not sure if I can close this issue. Thank you.

**Comment by jillawar** [comment]
I've closed it.. Yes thank you
