### ISSUE TITLE
Can't seem to move on from "Update Daisy's `favorite_color" lesson (id: 690)

### ISSUE THREAD

**Issue by willhousecreative** [coderoad/coderoad-vscode#576]
**Describe the bug**
First, thank you for creating this course. It has been a real joy to learn in this hand's on way. 

At present, I am in the process of working through the "Learn Relational Databases by Building a Mario Database" and am repeatedly getting stuck on the "Update Daisy's 'favorite_color'" lesson.

**To Reproduce**
1. Reset the tutorial (id: 690)
2. Log out and back in to the mario_database
3. Run "SELECT * FROM characters;"

TERMINAL OUTPUT:
+--------------+-----------+------------------+----------------+
| character_id |   name    |     homeland     | favorite_color |
+--------------+-----------+------------------+----------------+
|            1 | Mario     | Mushroom Kingdom | Red            |
|            2 | Luigi     | Mushroom Kingdom | Green          |
|            3 | Peach     | Mushroom Kingdom | Pink           |
|            4 | Toadstool | Mushroom Kingdom | Red            |
|            5 | Bowser    | Mushroom Kingdom | Green          |
+--------------+-----------+------------------+----------------+

4. Go back to the last step (id: 670, Add Daisy and Yoshi Rows) and reinsert the data (at this point I just copy/paste the command given in the hint)
5. Run "SELECT * FROM characters;"

TERMINAL OUTPUT:
+--------------+-----------+------------------+----------------+
| character_id |   name    |     homeland     | favorite_color |
+--------------+-----------+------------------+----------------+
|            1 | Mario     | Mushroom Kingdom | Red            |
|            2 | Luigi     | Mushroom Kingdom | Green          |
|            3 | Peach     | Mushroom Kingdom | Pink           |
|            4 | Toadstool | Mushroom Kingdom | Red            |
|            5 | Bowser    | Mushroom Kingdom | Green          |
|            6 | Daisy     | Sarasaland       | Yellow         |
|            7 | Yoshi     | Dinosaur Land    | Green          |
+--------------+-----------+------------------+----------------+

6. UPDATE the 'Daisy' row by copy/pasting the command that is given in the hint

TERMINAL OUTPUT: 
mario_database=> UPDATE 1

7: Run "SELECT * FROM characters;"

TERMINAL OUTPUT: 
+--------------+-----------+------------------+----------------+
| character_id |   name    |     homeland     | favorite_color |
+--------------+-----------+------------------+----------------+
|            1 | Mario     | Mushroom Kingdom | Red            |
|            2 | Luigi     | Mushroom Kingdom | Green          |
|            3 | Peach     | Mushroom Kingdom | Pink           |
|            4 | Toadstool | Mushroom Kingdom | Red            |
|            5 | Bowser    | Mushroom Kingdom | Green          |
|            7 | Yoshi     | Dinosaur Land    | Green          |
|            6 | Daisy     | Sarasaland       | Orange         |
+--------------+-----------+------------------+----------------+

8. Select the "Run" button
9. Prompt says: "characters" should have the correct rows for "Daisy" and "Yoshi"

                                                                                                   
**Expected behavior**
Given that I have completed what the task requires, Daisy's favorite color is now "Orange", I would expect to advance to the next lesson.

**Desktop:**
 - Platform: Mac
 - OS: MacOS Monterey
 - Version 12.1

**VSCode:**
 - Version  1.63.2

**Node:**
 - Version v16.13.1

**Git:**
 - Version 2.32.0 (Apple Git-132)

**Additional context**
I hope this gives all the context you may need. I appreciate any help in getting past this lesson so that I may complete the course. Happy to provide any further information if necessary.

**Comment by ShMcK** [comment]
Thanks Willhouse, this may be tutorial specific, I'll ping the tutorial creator: @moT01 .

**Comment by moT01** [comment]
Thanks for reporting @willhousecreative. This particular lesson seems to be problematic. There has been a few other people that have gotten stuck on it. There has been many who have gotten passed it as well - myself included. There's a [post on our forum](https://forum.freecodecamp.org/t/bug-in-building-a-mario-database/493206) where I attempt to troubleshoot it with others who were stuck here. I recommend looking over that to see if you can use any of those methods to get passed it. If they don't work, you can post a reply there and I, or maybe someone else, can weigh in to help.

I will take a look at the tutorial and see if there's something happening at that step that I can fix.

You can also close this issue - it's related to the tutorial and not CodeRoad. Thanks.

**Comment by willhousecreative** [comment]
Thanks @ShMcK and @moT01. Will take a look at the link you sent. Appreciate the help.
