### ISSUE TITLE
Can't move on in the SQL lesson because doesn't accept even the hint one.

### ISSUE THREAD

**Issue by bassamsdata** [coderoad/coderoad-vscode#598]
**Describe the bug**
There's a bug when trying update a name in SQL as requested, it shows that "You should have updated Tod's name' when I run the SQL command.

**To Reproduce**
1. Go to "Learn Relational Databases by Building a Mario Database".2. 
2. keep going until you reach this question "Her favorite color was updated. Toadstool's name is wrong as well, it's actually Toad. Use UPDATE to SET his name to Toad. Use the condition favorite_color='Red'."3. 
3. Try the full command in the hint option "UPDATE characters SET name='Toad' WHERE favorite_color='Red';"
it will show an error "You should have updated "Toad's" name" and then it won't continue the lesson and can't skip this one.

**Expected behavior**
just to continue to the next one.
I tried many things but couldn't work.

**Screenshots**
<img width="1251" alt="Screen Shot 2022-09-09 at 10 27 49 PM" src="https://user-images.githubusercontent.com/105807570/189465399-e7405b2f-26a9-4997-af6a-ec975d3846e8.png">

**Desktop (please complete the following information):**
 - Platform: Mac
 - OS: MACOS Monterey
 - Version 12.5.1

**VSCode (please complete the following information):**
 - Version v1.57.1

**Node (please complete the following information):**
 - Version [e.g. 12.4]

**Git (please complete the following information):**
 - Version [e.g. 2.24.1]

**Additional context**
code-server
code-server: v3.11.0
VS Code: v1.57.1
Commit: 7b8cd25c0c48b6a1799587ebbc9b09d6af7988f3
Date: 2021-07-22T14:42:48Z (1 yr ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15

**Comment by bassamsdata** [comment]
I closed all the browser and docker pages and reopened it and now it worked ! thanks

**Comment by ShMcK** [comment]
Thanks @bassamsdata!
@moT01 for visibility.

**Comment by moT01** [comment]
There's some [troubleshooting tips you can try here](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231#issues-within-a-course-9) @bassamsdata - I recommend resetting the step and trying it again. You may have changed something with one of your commands that the test is looking for. If that doesn't work, you should create a post [on the forum](https://forum.freecodecamp.org/) where someone can help you further. Thanks 👍
